// Main color palette
const mainPalette = {
  white: '#FFFFFF',
  black: '#000000',
  foreground: '#4A4A4A',
  gray: '#E5E5E5',
  lightGray: '#F2F2F2',
  pink: '#E91E63',
  pinkHover: '#C2185B',
  badgeGray: '#979797',
  badgeGrayHover: '#8C8C8C',
  badgeLightGray: '#B2B2B2',
  badgeLightGrayHover: '#ADADAD',
  purple: '#CE93D8',
  purpleHover: '#BA68C8',
  indigo: '#9FA8DA',
  indigoHover: '#7986CB',
  lightBlue: '#81D4FA',
  lightBlueHover: '#4FC3F7',
  teal: '#80CBC4',
  tealHover: '#4DB6AC',
  orange: '#FFCC80',
  orangeHover: '#FFB74D',
  brown: '#BCAAA4',
  brownHover: '#A1887F',
  blueGray: '#B0BEC5',
  blueGrayHover: '#90A4AE',
};

// Main font-family
const fontFamily = 'Sarabun, sans-serif';

// Main theme object
export default {
  fontFamily,
  fontBaseSize: '16px',
  white: mainPalette.white,
  black: mainPalette.black,
  foreground: mainPalette.foreground,
  gray: mainPalette.gray,
  lightGray: mainPalette.lightGray,
  btnBackground: mainPalette.pink,
  btnBackgroundHover: mainPalette.pinkHover,
  pink: mainPalette.pink,
  pinkHover: mainPalette.pinkHover,
  badgeGray: mainPalette.badgeGray,
  badgeGrayHover: mainPalette.badgeGrayHover,
  badgeLightGray: mainPalette.badgeLightGray,
  badgeLightGrayHover: mainPalette.badgeLightGrayHover,
  purple: mainPalette.purple,
  purpleHover: mainPalette.purpleHover,
  indigo: mainPalette.indigo,
  indigoHover: mainPalette.indigoHover,
  lightBlue: mainPalette.lightBlue,
  lightBlueHover: mainPalette.lightBlueHover,
  teal: mainPalette.teal,
  tealHover: mainPalette.tealHover,
  orange: mainPalette.orange,
  orangeHover: mainPalette.orangeHover,
  brown: mainPalette.brown,
  brownHover: mainPalette.brownHover,
  blueGray: mainPalette.blueGray,
  blueGrayHover: mainPalette.blueGrayHover
};
